import '@/app/core/global-style/globals.css'

export const metadata = {
  title: 'Plunge - Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
